apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hyperdao-api.app-name" . }}-docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
